#!/bin/sh
set -e

if [ "${LB_CONFIG_RUNNING}" = "1" ]; then
    exit 0
fi
export LB_CONFIG_RUNNING=1

lb config noauto \
  --distribution jammy \
  --architectures amd64 \
  --binary-images iso-hybrid \
  --archive-areas "main restricted universe multiverse" \
  --bootappend-live "boot=live components quiet splash" \
  --debian-installer none \
  --memtest none \
  --win32-loader false
